### ISSUE TITLE
파이어폭스에서 마우스 드래그로 그리드 컬럼 너비 조정이 불가

### ISSUE THREAD

**Issue by ghost** [things-factory/simple-ui#6]
컬럼 헤더에 커서를 대면 너비 조정 커서로 바뀌지만 실제로는 조정이 불가함

**Comment by lotstar87** [comment]
firefox 버그. (https://bugzilla.mozilla.org/show_bug.cgi?id=505521)
firefox에서 dragevent에 마우스 좌표를 포함하지 않는 문제

아래의 예제를 통해 확인 가능
https://bug505521.bmoattachments.org/attachment.cgi?id=9106354

**Comment by lotstar87** [comment]
firefox에서 해결되면 b3e27b5 를 revert할 것.
